'use client';
import { useEffect, useState, useRef } from 'react';
import { Flag, Radio, Play, Pause, ExternalLink, Copy, RotateCcw, ChevronRight, Check, Trophy } from 'lucide-react';
import { countries, initialState, acceptVote, type ArenaState } from '../lib/arena';
import {registerArenaTools} from '../lib/webmcp';
const KEY='flag-arena-demo-v1';
const flag=(code:string)=><span role="img" aria-label={countries.find(c=>c.code===code)?.name||code} className={`fi fi-${code.toLowerCase()}`}/>;
export default function Home(){
 const [state,setState]=useState<ArenaState>(initialState());
 const [overlay,setOverlay]=useState(false),[local,setLocal]=useState(false),[ready,setReady]=useState(false),[running,setRunning]=useState(false);
 const [message,setMessage]=useState('Indonesia'),[viewer,setViewer]=useState('Test viewer'),[notice,setNotice]=useState(''),[video,setVideo]=useState(''),[credential,setCredential]=useState('');
 const [busy,setBusy]=useState(false),[confirmReset,setConfirmReset]=useState(false);
 useEffect(()=>{
  setOverlay(new URLSearchParams(location.search).get('overlay')==='1');
  const isLocal=['localhost','127.0.0.1'].includes(location.hostname);setLocal(isLocal);
  if(!isLocal){try{const saved=localStorage.getItem(KEY);if(saved)setState(JSON.parse(saved));}catch{}setReady(true);
   const sync=(e:StorageEvent)=>{if(e.key===KEY&&e.newValue){try{setState(JSON.parse(e.newValue));}catch{}}};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);
  }
  const source=new EventSource('/api/events');source.onmessage=e=>{setState(JSON.parse(e.data));setReady(true);};source.onerror=()=>setNotice('Local connection interrupted. Keep Flag Arena running; reconnecting…');return()=>source.close();
 },[]);
 useEffect(()=>{if(ready&&!local){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{}}},[state,local,ready]);
 async function action(name:string,body:Record<string,unknown>={}){
  if(local){const r=await fetch(`/api/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Action could not be completed.');return data;}
  if(name==='vote'){const result=acceptVote(state,{id:crypto.randomUUID(),viewerId:String(body.viewer),viewer:String(body.viewer),text:String(body.text),time:Date.now()});if(result.accepted)setState(result.state);return result;}
  if(name==='reset'){setState(initialState());return {};}
  throw new Error('Use the local Flag Arena control panel to connect YouTube.');
 }
 useEffect(()=>{if(!running||state.mode==='live')return;const timer=setInterval(()=>{const c=countries[Math.floor(Math.random()*30)];void action('vote',{viewer:`Demo fan ${Math.floor(Math.random()*80)}`,text:c.name}).catch(e=>{setNotice(e.message);setRunning(false);});},950);return()=>clearInterval(timer);},[running,state,local]);
 const apiRef=useRef({state,action});apiRef.current={state,action};
 useEffect(()=>registerArenaTools(()=>({mode:apiRef.current.state.mode,scores:apiRef.current.state.scores}),async(viewer,text)=>{if(apiRef.current.state.mode==='live')throw new Error('Demo votes are disabled in live mode.');return apiRef.current.action('vote',{viewer,text});}),[]);
 const ranked=[...countries].sort((a,b)=>(state.scores[b.code]||0)-(state.scores[a.code]||0)||a.name.localeCompare(b.name));
 const total=Object.values(state.scores).reduce((a,b)=>a+b,0),leader=total?ranked[0]:undefined,latest=state.recent[0],active=ranked.filter(c=>state.scores[c.code]);
 const grid=(total?ranked:countries).slice(0,60),goal=(Math.floor(total/100)+1)*100;
 async function vote(e:React.FormEvent){e.preventDefault();try{const r=await action('vote',{viewer,text:message});setNotice(r.accepted?'+1 point! Vote counted.':r.reason);}catch(e){setNotice((e as Error).message);}}
 async function connect(e:React.FormEvent){e.preventDefault();setBusy(true);setRunning(false);try{await action('connect',{video,credential});setCredential('');setNotice('Connected. New chat votes will count from now on.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const board=<section className="arena" aria-label="Vertical stream scoreboard">
  <div className="arena-top"><span className="mini-brand"><Flag fill="currentColor"/> FLAG ARENA</span><span className="live-pill"><i/>{state.mode==='live'?(state.connected?'YOUTUBE LIVE':'CHAT PAUSED'):'DEMO MODE'}</span></div>
  <div className="arena-title"><span>ONE WORLD. ONE WINNER.</span><h2>REP YOUR<br/><em>COUNTRY.</em></h2><p>Type your country in chat to vote</p></div>
  <div className="leader-card"><div className="leader-label"><Trophy/>{leader?'CURRENT LEADER':'THE TOP SPOT IS OPEN'}</div><div className="leader-main">{leader?flag(leader.code):<Flag/>}<div><h3>{leader?.name||'Who goes first?'}</h3><span>{leader?'Your country could take the lead':'Every country starts at zero'}</span></div><strong>{leader?state.scores[leader.code].toLocaleString():'—'}<small>VOTES</small></strong></div></div>
  <div className="board-heading"><span>WORLD LEADERBOARD</span><span>{active.length} countries in play</span></div>
  <div className="flag-grid">{grid.map((c,i)=><div key={c.code} className={`country-tile ${latest?.code===c.code?'just-voted':''} ${leader?.code===c.code?'first':''}`} title={`${c.name}: ${state.scores[c.code]||0} votes`}><small>{String(i+1).padStart(2,'0')}</small>{flag(c.code)}<span>{c.name}</span><strong>{(state.scores[c.code]||0).toLocaleString()}</strong></div>)}</div>
  <section className="stream-chat" aria-label="Recent viewer votes"><div className="chat-heading"><Radio size={14}/>{state.mode==='live'?'VIEWER CHAT':'DEMO VIEWER CHAT'}</div>{state.recent.length?state.recent.slice(0,3).map(v=><div className="stream-chat-row" key={v.id}>{flag(v.code)}<div><b title={v.viewer}>{v.viewer}</b><p title={v.text}>{v.text}</p></div><strong>+1</strong></div>):<p className="chat-placeholder">Your viewers’ names and country votes appear here.</p>}</section>
  <div className="milestone"><div><span>THE NEXT MILESTONE</span><b>{total.toLocaleString()} <small>/ {goal.toLocaleString()} votes</small></b></div><div className="progress"><i style={{width:`${total%100}%`}}/></div></div>
  <div className="arena-footer"><b>1 CHAT = 1 VOTE</b><span>One vote every 10 seconds</span></div>
 </section>;
 if(overlay)return <main className="overlay-only">{board}</main>;
 return <main className="studio"><header className="studio-header"><a className="brand" href="/"><span><Flag size={20} fill="currentColor"/></span>Flag Arena <small>STUDIO</small></a><div className="header-right"><span className="status-dot"/>{state.connected?'YouTube connected':'Stream not connected'}</div></header>
 <div className="workspace"><aside className="controls"><div className="eyebrow">YOUR STREAM, YOUR ARENA</div><h1>Let the world<br/>pick a side.</h1><p className="intro">Turn your live chat into a country competition. Every vote moves the leaderboard.</p>
 <div className="control-card"><div className="card-title"><span className="step">01</span><h2>Try the arena</h2><span className="tag">DEMO</span></div><p>See the scoreboard react before going live. Demo votes stay separate from your stream.</p><button className="primary" disabled={!ready||state.mode==='live'} onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16} fill="currentColor"/>}{running?'Pause demo':'Start demo'}<ChevronRight size={16}/></button><form onSubmit={vote}><label htmlFor="viewer">Test viewer</label><input id="viewer" maxLength={60} value={viewer} onChange={e=>setViewer(e.target.value)} required/><label htmlFor="message">Try a chat vote</label><div className="input-row"><input id="message" maxLength={200} value={message} onChange={e=>setMessage(e.target.value)} required/><button disabled={!ready||state.mode==='live'} type="submit" aria-label="Send test vote"><ChevronRight size={19}/></button></div><small>Country name, flag emoji, or !vote ID</small></form></div>
 <div className="control-card"><div className="card-title"><span className="step">02</span><h2>Connect YouTube</h2></div>{local?<form onSubmit={connect}><p>When your stream is live, paste its link and a YouTube Data API key. The key stays in this local server’s memory.</p><label htmlFor="video">Livestream URL</label><input id="video" placeholder="https://youtube.com/watch?v=…" value={video} onChange={e=>setVideo(e.target.value)} required/><label htmlFor="credential">YouTube Data API key</label><input id="credential" type="password" autoComplete="off" value={credential} onChange={e=>setCredential(e.target.value)} required/><button className="secondary" disabled={busy||state.connected}>{busy?'Connecting…':'Connect live chat'}</button>{state.mode==='live'&&<button type="button" className="text-button" onClick={()=>void action('disconnect').catch(e=>setNotice(e.message))}>Disconnect chat</button>}</form>:<p>This preview uses demo votes. Connect real YouTube chat from the local Flag Arena app on your streaming PC.</p>}<div className="connection-info"><span className="status-dot"/>{state.status}</div></div>
 <div className="control-card"><div className="card-title"><span className="step">03</span><h2>Add to OBS</h2></div><p>Add a Browser Source. Set its width to <b>1080</b> and height to <b>1920</b>.</p><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?overlay=1`);setNotice('Overlay URL copied.');}catch{setNotice(`Overlay URL: ${location.origin}/?overlay=1`);}}}><Copy size={15}/>Copy overlay URL</button><a className="text-button" href="/?overlay=1" target="_blank" rel="noreferrer">Open clean overlay <ExternalLink size={13}/></a>{!local&&<small>Use the local app’s overlay URL in OBS to share live scores.</small>}</div>
 <div className="rules"><b>Fair play, built in</b><p>1 point per message · 10-second viewer cooldown<br/>One country per vote · No paid points</p></div></aside>
 <section className="preview-section"><div className="preview-heading"><span><i/> STREAM PREVIEW</span><small>9:16 · 1080 × 1920</small></div><div className="preview-shell">{board}</div><div className="preview-caption"><Check size={14}/>Only the scoreboard appears in your OBS overlay</div></section>
 <aside className="activity"><div className="activity-title"><Radio size={18}/><h2>Arena activity</h2></div><div className="stats"><div><span>Total votes</span><strong>{total.toLocaleString()}</strong></div><div><span>Countries</span><strong>{active.length}</strong></div></div><div className="activity-label">RECENT VOTES <span>{state.mode==='live'?'LIVE':'DEMO'}</span></div><div className="feed">{state.recent.length?state.recent.slice(0,8).map(v=><div className="feed-item" key={v.id}>{flag(v.code)}<div><b>{v.viewer}</b><span>{countries.find(c=>c.code===v.code)?.name}</span></div><strong>+1</strong></div>):<div className="empty-feed"><Flag size={28}/><b>A world of possibilities.</b><p>Start the demo or send a test vote.<br/>Your supporters will appear here.</p></div>}</div><div className="reset-area">{confirmReset?<><p>Clear all scores?</p><button className="secondary" onClick={async()=>{try{setRunning(false);await action('reset');setConfirmReset(false);setNotice('Scores reset.');}catch(e){setNotice((e as Error).message);}}}>Yes, reset scores</button><button className="text-button" onClick={()=>setConfirmReset(false)}>Cancel</button></>:<button className="text-button" onClick={()=>setConfirmReset(true)}><RotateCcw size={13}/>Reset scores</button>}</div></aside></div>
 {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}</main>;
}
